# Generated by Django 5.0 on 2024-01-23 09:44

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank',
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'payment_methods', 'verbose_name_plural': 'payment_methods'},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='subscribe',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(default=None, max_length=64, verbose_name='نام بانک'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='Payment_Methods',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='payments.paymentmethod', verbose_name='بانک')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='payments.subscribe', verbose_name='اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'Payment',
            },
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
