# Generated by Django 5.0 on 2024-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='anime_type',
            field=models.CharField(blank=True, choices=[('سینمایی', 'movie'), ('سریالی', 'series'), ('ova', 'ova')], max_length=64, null=True, verbose_name='نوع انیمه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='عنوان'),
        ),
    ]
