# Generated by Django 5.0 on 2024-01-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categories_category_rename_episodes_episode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Director',
            new_name='director',
        ),
    ]
