# Generated by Django 5.0 on 2024-01-22 12:41

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_movie_anime_type_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='season',
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='products.movie', verbose_name='فیلم')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='products.season', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'serial',
                'verbose_name_plural': 'series',
                'db_table': 'Serial',
            },
        ),
    ]
