# Generated by Django 5.0 on 2024-01-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_director_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Translator',
            new_name='translator',
        ),
    ]
