# Generated by Django 5.0 on 2024-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_movie_season_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rate',
            field=models.FloatField(verbose_name='رتبه imdb'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ongoing_day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'شنبه'), (2, 'یکشنبه'), (3, 'دوشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], db_default=models.Value(False), verbose_name='روز پخش'),
        ),
    ]
