# Generated by Django 5.0 on 2024-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_movie_imdb_rate_alter_movie_ongoing_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['file'], 'verbose_name': 'episode', 'verbose_name_plural': 'episodes'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_ongoing',
            field=models.BooleanField(db_default=models.Value(False), verbose_name='در حال پخش'),
        ),
    ]
