# Generated by Django 5.0 on 2024-01-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_translator_movie_translator'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه'),
        ),
    ]
