# Generated by Django 5.0 on 2024-01-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_slug_alter_episode_file_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=None, max_length=62, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
