# Generated by Django 5.0 on 2024-01-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_season_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('هاردساب', 'هاردساب'), ('هاردساب اختصاصی', 'هاردساب اختصاصی'), ('دوبله فارسی', 'دوبله فارسی')], max_length=62, null=True, verbose_name='زبان ترجمه'),
        ),
        migrations.AlterField(
            model_name='season',
            name='language',
            field=models.CharField(choices=[('دوبله فارسی', 'دوبله فارسی'), ('زیرنویس چسبیده', 'زیرنویس چسبیده'), ('زبان اصلی', 'زبان اصلی')], max_length=62, verbose_name='زبان (زیرنویس) (دوبله)'),
        ),
    ]
