# Generated by Django 5.0 on 2024-01-25 12:11

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_movie_language_alter_season_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('year', models.CharField(max_length=62, verbose_name='سال')),
            ],
            options={
                'verbose_name': 'year',
                'verbose_name_plural': 'years',
                'db_table': 'Years',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='products.years', verbose_name='سال پخش'),
        ),
    ]
