# Generated by Django 5.0 on 2024-02-14 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_years_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(upload_to='products/files', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='products/images/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='products.years', verbose_name='سال پخش'),
            preserve_default=False,
        ),
    ]
