# Generated by Django 5.0 on 2024-01-21 14:51

import django_jalali.db.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('username', models.CharField(error_messages={'invalid': 'نام کاربری باید از حروف,اعداد و ـ باشد', 'unique': 'کاربری با این نام وجود دارد'}, max_length=64, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(error_messages={'invalid': 'لطفا یک ایمیل معتبر وارد کنید', 'unique': 'کاربری با این ایمیل وجود دارد'}, max_length=64, unique=True, verbose_name='ایمیل')),
                ('password', models.CharField(error_messages={'invalid': 'رمز کاربری باید ۸ کاراکتر یا بیشتر باشد و یک حرف بزرگ  و یک عدد داشته باشد'}, max_length=64, verbose_name='رمز عبور')),
                ('last_password_reset', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین تغییر رمزعبور')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام خانوادگی')),
                ('city', models.CharField(blank=True, db_index=True, max_length=55, null=True, verbose_name='شهر')),
                ('is_superuser', models.BooleanField(db_default=models.Value(False), db_index=True, verbose_name='ادمین')),
                ('is_staff', models.BooleanField(db_default=models.Value(False), db_index=True, verbose_name='کارکنان')),
                ('ipaddress', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='ایپی آدرس')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['created_at'],
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
