# Generated by Django 5.0 on 2024-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/users/default.jpg', upload_to='media/users/', verbose_name='آواتار'),
        ),
    ]
