# Generated by Django 5.0 on 2024-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='سن'),
        ),
    ]
