# Generated by Django 5.0 on 2024-01-21 15:12

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ایپی آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='وضعیت')),
                ('subject', models.CharField(max_length=252, verbose_name='موضوغ')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/ticket/', verbose_name='فایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'ticket',
            },
        ),
    ]
