# Generated by Django 5.0 on 2024-01-22 10:21

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categories_category_rename_episodes_episode_and_more'),
        ('users', '0004_alter_user_city_alter_user_ipaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='وضعیت')),
                ('text', models.TextField(verbose_name='متن')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='products.movie', verbose_name='فیلم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'Comment',
            },
        ),
    ]
