# Generated by Django 5.0 on 2024-01-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_ticket_table_ticketrely'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketRely',
            new_name='TicketReply',
        ),
    ]
