# Generated by Django 5.0 on 2024-01-22 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_ticketrely_ticketreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='user',
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='users.ticket', verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
