# Generated by Django 5.0 on 2024-01-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_ticketreply_user_ticketreply_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='users.ticket', verbose_name='تیکت'),
        ),
    ]
