# Generated by Django 5.0 on 2024-01-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ticketreply_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='is_active',
        ),
    ]
