# Generated by Django 5.0 on 2024-02-15 10:45

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'لطفا یک ایمیل معتبر وارد کنید', 'unique': 'کاربری با این ایمیل وجود دارد'}, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})$', code='invalid', message='ایمیل وارد شده معتبر نمی باشد')], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(error_messages={'invalid': 'رمز کاربری باید ۸ کاراکتر یا بیشتر باشد و یک حرف بزرگ  و یک عدد داشته باشد'}, max_length=254, validators=[django.core.validators.RegexValidator('^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$', code='valid', message='رمز عبور حداقل باید ۸ کاراکتر یا بیشتر باشد و حداقل یک حرف بزرگ و یک عدد داشته باشد')], verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'invalid': 'نام کاربری باید از حروف,اعداد و ـ باشد', 'unique': 'کاربری با این نام وجود دارد'}, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('([a-zA-Z0-9_]+)', code='invalid', message='نام کاربری باید از حروف اعداد و ـ باشد')], verbose_name='نام کاربری'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('is_read', models.BooleanField(blank=True, default=False, verbose_name='خوانده شده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'Notification',
            },
        ),
    ]
