# Generated by Django 5.0 on 2024-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.DurationField(blank=True, null=True, verbose_name='زمان اشتراک'),
        ),
    ]
