# Generated by Django 5.0 on 2024-02-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اشتراک'),
        ),
    ]
