# Generated by Django 5.0 on 2024-02-17 11:10

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_password_reset',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='زمان آخرین تغییر رمزعبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(error_messages={'invalid': 'رمز کاربری باید ۸ کاراکتر یا بیشتر باشد و یک حرف بزرگ  و یک عدد داشته باشد'}, max_length=254, validators=[django.core.validators.RegexValidator('^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$', code='valid', message='')], verbose_name='رمز عبور'),
        ),
    ]
