# Generated by Django 5.0 on 2024-02-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_ticket_is_active_ticket_admin_closed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_close',
            new_name='user_closed',
        ),
    ]
