# Generated by Django 5.0 on 2024-02-17 16:42

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_user_close_ticket_user_closed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketReply',
            new_name='TicketAdminReply',
        ),
        migrations.CreateModel(
            name='TicketUserReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/ticket/', verbose_name='فایل')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='users.ticket', verbose_name='تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ticket_user_reply',
                'verbose_name_plural': 'ticket_user_replies',
                'db_table': 'TickTicketUserReplyet',
            },
        ),
    ]
