# Generated by Django 5.0 on 2024-02-17 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_ticketreply_ticketadminreply_ticketuserreply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketUserReply',
            new_name='TicketDetails',
        ),
        migrations.AlterModelOptions(
            name='ticketdetails',
            options={'verbose_name': 'ticket_detail', 'verbose_name_plural': 'ticket_details'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='message',
        ),
        migrations.AddField(
            model_name='ticketadminreply',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterModelTable(
            name='ticketdetails',
            table='TicketDetails',
        ),
    ]
