# Generated by Django 5.0 on 2024-02-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_ticketuserreply_ticketdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketadminreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='users.ticketdetails', verbose_name='تیکت'),
        ),
    ]
