# Generated by Django 5.0 on 2024-02-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_reply_dislike_reply_like_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.IntegerField(default=False, verbose_name='دیس لایک'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0, verbose_name='لایک'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='dislike',
            field=models.IntegerField(default=False, verbose_name='دیس لایک'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='like',
            field=models.IntegerField(default=0, verbose_name='لایک'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='users.comment', verbose_name='پاسخ به'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
    ]
